### ISSUE TITLE
Messaging

### ISSUE THREAD

**Issue by NotAxel** [NotAxel/Matchup#21]
Allow players to see other online players and choose who they want to play with 
#1, #2, #3, #4, #5, #6, #7, #8, #9, #10, #11, #12, #13, #14, #15, #16, #17, #18

**Comment by NotAxel** [comment]
2 releases
1) Show players who have an account Estimation = 8 hours
2) Filter accounts (people who are online, characters... etc) Estimation = 15 hours
Total Estimation = 23 hours

**Comment by garretpoole** [comment]
Evan / Nageek

**Comment by Harmless19** [comment]
Not completed in sprint 2 due to difficulties using flutter for messaging - we are looking into using the firebase messaging library to implement messaging
