### ISSUE TITLE
Friends List front end

### ISSUE THREAD

**Issue by Harmless19** [NotAxel/Matchup#35]
Create a front end page for the friends list. Clicking on a user in the friends list should take the user to that friends profile. Add a button next to names of friends that will act as a "message friend button" which will take the user to their conversation with that friend or create a new one if no conversation exists

**Comment by efukumoto17** [comment]
estimated 4hrs

**Comment by efukumoto17** [comment]
took 2 hrs

**Comment by efukumoto17** [comment]
actually took 4hrs
