### ISSUE TITLE
Skill level at signup

### ISSUE THREAD

**Issue by bbdunning** [NotAxel/Matchup#52]
Add options at signup time to select what skill group a player is in.  This should automatically be placed in filters and be able to be changed later.

**Comment by Harmless19** [comment]
i will do the userInfoEntry page side of things for this

**Comment by Harmless19** [comment]
expected 1 hour

**Comment by Harmless19** [comment]
estimated time: 2 hours

**Comment by Harmless19** [comment]
actual time: 3 hours
completed by kyle
