### ISSUE TITLE
Invalid emails allowed

### ISSUE THREAD

**Issue by fuzzything44** [NotAxel/Matchup#55]
When registering, entering "me@e.eeee" is accepted as an email, even though "eeee" is not a valid top-level domain, meaning it is not a valid email address.

**Comment by fuzzything44** [comment]
Label: defect

**Comment by Harmless19** [comment]
https://davidcel.is/posts/stop-validating-email-addresses-with-regex/
Emails like these will be able validated with an email confirmation link sent to the given email
