### ISSUE TITLE
Back button from challenge brings you to main page

### ISSUE THREAD

**Issue by fuzzything44** [NotAxel/Matchup#58]
When on page to challenge an individual person, the back button takes you back to main page. Expected that it takes you to the challenger list page.

**Comment by fuzzything44** [comment]
Label: enhancement

**Comment by Harmless19** [comment]
there is a bigger problem with how the routing from the homepage is set up that is causing this to happen. home page needs redesign

**Comment by Harmless19** [comment]
fixed by wrapping all of the tab destinations in their own navigators to provide parallel navigation
